config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/table'
  get 'home/chart'

  match 'surveys', to: 'home#table', via: :all
  match 'charts', to: 'home#charts', via: :all
  
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'open-uri'

class HomeController < ApplicationController
  def index
    @surveys = load_surveys
  end

  def table
    @symptoms = load_symptoms
    @surveys = load_surveys
    @users = load_survey_users
  end

  def charts
    @surveys = load_surveys
    @users = load_users

    @total_symptoms = @surveys.count
    @total_syndromes = Hash.new(0)
    @total_symptoms_by_day = Hash.new(0)
    @total_no_symptoms_by_day = Hash.new(0)

    @surveys.each do |survey|
      day = DateTime.parse(survey["createdAt"]).strftime("%d").to_i

      if survey["no_symptom"] == "N"
        @total_symptoms_by_day[day] += 1
      else
        @total_no_symptoms_by_day[day] += 1
      end
    end

    @total_users = @users.count
    @total_users_by_day = Hash.new(0)

    @users.each do |user|
      day = DateTime.parse(user["createdAt"]).strftime("%d").to_i
      @total_users_by_day[day] += 1
    end
  end

  protected

  def load_symptoms
    api_host=ENV["GDS_API_HOST"] || "localhost"
    api_port=ENV["GDS_API_PORT"] || "80"
    symptoms_json = ActiveSupport::JSON.decode(open("http://#{api_host}:#{api_port}/symptoms/get").read)

    symptoms = {}

    symptoms_json['data'].each do |sympton|
      symptoms[sympton['code']] = sympton['name']
    end

    symptoms
  end

  def load_surveys
    api_host=ENV["GDS_API_HOST"] || "localhost"
    api_port=ENV["GDS_API_PORT"] || "80"
    json = ActiveSupport::JSON.decode(open("http://#{api_host}:#{api_port}/surveys/a").read)

    # json['data'].each do |survey|
    #   survey["info"] = DateTime.parse(survey["createdAt"]).strftime("%d/%m/%Y").to_s
    #
    #
    #   symptoms = check_symptoms survey
    #   syndromes = check_syndromes survey
    #
    #   if symptoms.length > 0
    #     survey["symptoms"] = symptoms
    #     survey["info"] << " - " + symptoms
    #   end
    #
    #   if syndromes.length > 0
    #     survey["syndromes"] = syndromes
    #     survey["info"] << " - " + syndromes
    #   end
    #
    # end

    return json["data"]
  end

  def load_survey_users
    api_host=ENV["GDS_API_HOST"] || "localhost"
    api_port=ENV["GDS_API_PORT"] || "80"
    json = ActiveSupport::JSON.decode(open("http://#{api_host}:#{api_port}/users/a_with_ids").read)

    return json["data"]
  end

  def load_users
    api_host=ENV["GDS_API_HOST"] || "localhost"
    api_port=ENV["GDS_API_PORT"] || "80"
    json = ActiveSupport::JSON.decode(open("http://#{api_host}:#{api_port}/users/a").read)

    return json["data"]
  end

  def check_symptoms(survey)
    symptoms = []

    symptoms << "Febre" if survey.key?("FEBRE")
    symptoms << "Tosse" if survey.key?("TOSSE")
    symptoms << "Dor Garganta" if survey.key?("DORGARGA")
    symptoms << "Falta de Ar" if survey.key?("FALTAAR")
    symptoms << "Nausea e Vômito" if survey.key?("NAUSVOM")
    symptoms << "Diarreia" if survey.key?("DIARREIA")
    symptoms << "Sangramento" if survey.key?("SANGRAME")
    symptoms << "Manchas Vermelhas" if survey.key?("MANVERM")
    symptoms << "Dor no Corpo" if survey.key?("DORCORPO")
    symptoms << "Dor Juntas" if survey.key?("DORJUNTAS")
    symptoms << "Dor de Cabeça" if survey.key?("DORCABECA")
    symptoms << "Coceira" if survey.key?("COCEIRA")
    symptoms << "Olhos Vermelhos" if survey.key?("OLHOSVERM")

    return symptoms.join(', ')
  end

  def check_syndromes(survey)
    syndromes = []

    syndromes << "Exantematica" if survey["exantematica"] == true
    syndromes << "Diarreica" if survey["diarreica"] == true
    syndromes << "Respiratoria" if survey["respiratoria"] == true

    return syndromes.join(', ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/charts.html.erb
    <% days = (Date.parse("Wed, 28 Jun 2017 00:00:00 -0300")..Date.today).map{ |date| date.strftime("%d") } %>
    <% with_symptoms = days.map{ |day| @total_symptoms_by_day[day.to_i] } %>
    <% without_symptoms = days.map{ |day| @total_no_symptoms_by_day[day.to_i] } %>

    <center>
      <div style="width:65%;">
          <canvas id="surveys"></canvas>
          <br/><br/><br/>
          <canvas id="users"></canvas>
          <br/><br/><br/>
          <div id="canvas-holder" style="width:40%">
              <canvas id="syndromes"></canvas>
          </div>
      </div>
    </center>
    <script>
        /* --------------- Syndromes ------------ */
        var config_syndromes = {
            type: 'pie',
            data: {
                datasets: [{
                    data: [<%= @total_syndromes.values.join(', ') %>],
                    backgroundColor: [
                        window.chartColors.red,
                        window.chartColors.yellow,
                        window.chartColors.green,
                    ],
                    label: 'Síndromes'
                }],
                labels: [
                    "Exantematica",
                    "Diarreica",
                    "Respiratoria",
                ]
            },
            options: {
                responsive: true
            }
        };

        var ctx_syndromes = document.getElementById("syndromes").getContext("2d");
        window.myPie = new Chart(ctx_syndromes, config_syndromes);

        /* --------------- Users ------------ */

        var config_users = {
            type: 'line',
            data: {
                labels: [<%= @total_users_by_day.keys.join(', ') %>],
                datasets: [
                {
                    label: "Usuarios Registrados",
                    backgroundColor: window.chartColors.yellow,
                    borderColor: window.chartColors.yellow,
                    data: [ <%= @total_users_by_day.values.join(', ') %> ],
                    fill: false,
                },
                ]
            },
            options: {
                responsive: true,
                title:{
                    display:true,
                    text:'Usuarios (Total: <%= @total_users %>)'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Día'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Uusuarios Registrados'
                        }
                    }]
                }
            }
        };

        var ctx_users = document.getElementById("users").getContext("2d");
        window.myLine = new Chart(ctx_users, config_users);

        /* --------------- Surveys ------------ */

        var config_surveys = {
            type: 'line',
            data: {
                labels: [<%= days.join(', ') %>],
                datasets: [
                {
                    label: "Sintomático",
                    backgroundColor: window.chartColors.red,
                    borderColor: window.chartColors.red,
                    data: [ <%= with_symptoms.join(', ') %> ],
                    fill: false,
                },
                {
                    label: "No Es Sintomático",
                    backgroundColor: window.chartColors.blue,
                    borderColor: window.chartColors.blue,
                    data: [ <%= without_symptoms.join(', ') %> ],
                    fill: false,
                }

                ]
            },
            options: {
                responsive: true,
                title:{
                    display:true,
                    text:'Informe (Total: <%= @total_symptoms %>)'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Día'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Informe'
                        }
                    }]
                }
            }
        };

        var ctx_surveys = document.getElementById("surveys").getContext("2d");
        window.myLine = new Chart(ctx_surveys, config_surveys);

    </script>

app/views/home/index.html.erb
  <div id="map"></div>

  <script>
    $( document ).ready(function() {
      lat = 3.733;
      lon = -73.378;

      var map = L.map('map', {fullscreenControl: true, zoomControl: false}).setView([lat, lon], 6);
      var hash = new L.Hash(map);

      $(window).on("resize", function () { $("#map").height($(window).height() - 60); map.invalidateSize(); }).trigger("resize");

      L.tileLayer('https://a.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: 'Guardianes de la Salud | OpenStreetMap', maxZoom: 18,}).addTo(map);
      L.control.zoom({position:'topright'}).addTo(map);

      map.addControl( new L.Control.Search({
		url: 'http://nominatim.openstreetmap.org/search?format=json&q={s}',
		jsonpParam: 'json_callback',
		propertyName: 'display_name',
		propertyLoc: ['lat','lon'],
		marker: L.circleMarker([0,0],{radius:30}),
		autoCollapse: true,
		autoType: false,
		minLength: 2
	}) );

      var markers = L.markerClusterGroup();

      var IconBad = L.icon({ iconUrl: '<%= image_url "leaflet/images/icon_bad_small.png" %>', iconSize: [83, 83] });
      var IconGood = L.icon({ iconUrl: '<%= image_url "leaflet/images/icon_good_small.png" %>', iconSize: [83, 83] });

      <% @surveys.each do |survey| %>
        <% if survey["lat"] and survey["lon"] %>
          <% if survey["no_symptom"] == 'N' %>
            markers.addLayer(L.marker(L.latLng([<%= survey["lat"] %>, <%= survey["lon"] %>]), {icon: IconBad}).bindPopup('<%= survey["info"] %>')).addTo(map);
          <% else %>
            markers.addLayer(L.marker(L.latLng([<%= survey["lat"] %>, <%= survey["lon"] %>]), {icon: IconGood}).bindPopup('<%= survey["info"] %>')).addTo(map);
          <% end %>
        <% end %>
      <% end %>
    });
  </script>

app/views/home/table.html.erb
<meta http-equiv="refresh" content="120">

<table class="table" id="surveys">
 <thead>
  <tr>
    <th>Fecha de registro</th>
    <th>Hora de registro</th>
    <th>Departamento de registro</th>
    <th>Ciudad de registro</th>
    <th>Dirección</th>
    <th>ID usuario</th>

    <!--About user-->
    <th>ID de registro</th>
    <th>Parentesco</th>
    <th>Sexo</th>
    <th>Edad</th>
    <th>Grupo etário</th>
    <th>Pais de residencia</th>
    <th>Departamento de residencia</th>
    <th>Ciudad de residencia</th>
    <th>Raza</th>

    <!--About survey-->
    <th>Estado de salud</th>
    <th>Días con síntomas</th>
    <% @symptoms.each do |key, symptom| %>
      <th><%= symptom %></th>
    <% end %>
    <th>Contacto con enfermo</th>
    <th>Búsqueda IPS</th>
    <th>Antecedente de viaje</th>
    <th>País donde estuvo</th>
    <th>Departamento donde estuvo</th>
    <th>Ciudad donde estuvo</th>

  </tr>
 </thead>
 <tbody>
   <% @surveys.each do |survey| %>
     <% alert = "table-success" %>
     <% alert = "table-danger" if survey["no_symptom"] == "N" %>
     <tr class="<%= alert %>">
        <!-- About register -->
        <td><%= DateTime.parse(survey["createdAt"]).strftime("%d/%m/%Y") %></td> <!--Fecha de Registro -->
        <th><%= DateTime.parse(survey["createdAt"]).strftime("%H:%M") %></td> <!-- Hora de registro -->
        <td><%= survey["state"] %></td> <!-- Departamento de registro -->
        <td><%= survey["city"] %></td> <!-- Ciudad de registro -->
        <td><%= survey["formattedAddress"] %><!-- Dirección -->
        <td><%= survey["user"] %></td> <!-- Departamento de registro -->

        <!--About survey user -->
        <% survey_user_id = survey["household"] || survey["user"] %>
        <% survey_user = @users[survey_user_id] %>
        <% if survey_user %>
          <td><%= survey_user_id %></td> <!-- ID de registro --> 
          <td><%= ((!survey_user["relationship"]) or survey_user["relationship"] == "") ? "N/A" : survey_user["relationship"] %></td><!-- Parentesco -->
          <td><%= survey_user["gender"] %></td><!-- Sexo -->
          <td><%= survey_user["age"] %></td><!-- Age -->
          <td><%= survey_user["ageGroup"] %></td><!-- Age Group -->
          <td><%= survey_user["country"] %></td><!-- País de residencia -->
          <td><%= survey_user["state"] %></td><!-- Departamento de residencia -->
          <td><%= survey_user["city"] %></td><!-- Ciudad de residencia -->
          <td><%= survey_user["race"] %></td><!-- Raza -->
        <% else %>
          <td>INVALIDO</td>
          <td>INVALIDO</td>
          <td>INVALIDO</td>
          <td>INVALIDO</td>
          <td>INVALIDO</td>
          <td>INVALIDO</td>
        <% end %>

        <!-- About survey -->
        <td><%= survey["no_symptom"] == "N" ? "Bien" : "Mal" %></td>
        <td><%= survey["no_symptom"] == "Y" and  survey["startTime"] != "" ? "N/A" : ((DateTime.parse(survey["createdAt"]).to_time -
                 DateTime.parse(survey["startDate"]).to_time) /
                 86400).to_i %></td><!-- Días con síntomas -->
        <% @symptoms.each do |key, symptom| %>
         <td><%= survey[key].blank? ? 'No' : 'Si' %></td>
        <% end %>
        <td><%= survey["hadContagiousContact"] ? "Si" : "No" %></td><!-- Contacto con enfermo -->
        <td><%= survey["hadHealthCare"] ? "Si" : "No" %></td><!-- Búsqueda IPS -->
        <td><%= survey["hadTravelAbroad"] ? "Si" : "No" %></td><!-- Antecedente de viaje -->
        <td><%= survey["originCountry"] == "" ? survey["originCountry"] : "N/A" %></td><!-- Pais donde estuvo -->
        <td><%= survey["originState"] == "" ? survey["originState"] : "N/A" %></td><!-- Departamento donde estuvo -->
        <td><%= survey["originCity"] == "" ? survey["originCity"] : "N/A" %></td><!-- Ciudad donde estuvo -->
     </tr>
   <% end %>
 </tbody>
</table>

<script>
$(document).ready(function(){
    $('#surveys').DataTable({
      "lengthMenu": [[25, 50, 75, 100, -1], [25, 50, 75, 100, 'All']],
      "order": [],
      "stateSave": true,
      "dom": 'l&nbsp;Bfrtip',
      "buttons": [ { extend: 'copy', className: 'btn btn-primary' },
                 { extend: 'csv', className: 'btn btn-primary' },
                 { extend: 'excel', className: 'btn btn-primary' },
                 { extend: 'pdf', className: 'btn btn-primary' },
                 { extend: 'print', className: 'btn btn-primary' },]
    });
});
</script>

app/views/layouts/_footer.html.erb
    <br/>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">
          <a href="https://gitlab.com/centeias/gds-dashboard" target="_blank">Guardianes de la Salud - <i>Dashboard</i> (beta)</a> - GPLv3
        </span>
      </div>
    </footer>

app/views/layouts/_main.html.erb
  <div class="container">
    <%= yield %>
  </div>

app/views/layouts/_menu.html.erb
  <nav class="navbar navbar-toggleable-md navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        &#9776;
      </button>

      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <%= link_to("Inicio", root_path, :class => "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link_to("Informe", surveys_path, :class => "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link_to("Gráficos", charts_path, :class => "nav-link") %>
          </li>
        </ul>
      </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Guardianes de la Salud - Dashboard">
    <meta name="author" content="CENTEIAS">

    <title>Guardianes de la Salud - Dashboard</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/menu' %>
    <%= render 'layouts/main' %>
    <%= render 'layouts/footer' %>

  </body>
</html>